FROM ruby:2.5.5-alpine3.9

RUN apk add --no-cache --update build-base \
    linux-headers \
    git \
    postgresql-dev \
    nodejs \
    tzdata

ARG DATABASE_URL="postgres://postgres@db"
ARG RAILS_ENV=production

WORKDIR /myapp
COPY ./Gemfile /myapp/Gemfile

RUN gem install bundler
RUN bundle install

COPY . /myapp

RUN gem install aws-partitions -v 1.203.0
RUN gem install aws-sdk-core -v 3.63.0

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

CMD rails server -b 0.0.0.0
